/* Generate the structured data that has a source of truth elsewhere.

   The business itself is written by hand in global-sections/header.html,
   because its facts are stable and few. These two are not:

     FAQPage        the 25 questions in help-center.html. Kept in step
                    by reading that page's own <dl> pairs, so the
                    answer a machine gets is the answer a visitor
                    reads, and editing one cannot silently leave the
                    other behind.

     Offer catalogue  every size and rate on the location page, read
                    from the live feed, the same source the visible
                    table comes from.

   RUN IT after editing the Help Center, or when rates change:
     node tools/build-schema.js

   It rewrites only what is between the BEGIN and END markers. */
'use strict';

const fs = require('fs');
const path = require('path');

const ENDPOINT = 'https://cap-rock-self-storage.vercel.app/api/wss';
const FACILITY = 'lubbock-2213-n-quaker';
const ROOT = path.join(__dirname, '..');
const BUSINESS = 'https://caprock-storage.com/#business';

const BEGIN = '<!-- BEGIN SCHEMA: generated by tools/build-schema.js, do not hand edit -->';
const END = '<!-- END SCHEMA -->';

/* ---- turning markup back into text ----
   The answers contain links and non-breaking spaces. Structured data
   wants the sentence a person would read aloud, so the tags come out
   and the entities go back to being characters. */
const ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ',
  hellip: '…', times: '×', ndash: '–', mdash: '—',
  rsquo: '’', lsquo: '‘', ldquo: '“', rdquo: '”',
  copy: '©', deg: '°',
};

function plain(html) {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&(\w+);/g, (_, n) => (ENTITIES[n] !== undefined ? ENTITIES[n] : '&' + n + ';'))
    .replace(/\s+/g, ' ')
    .trim();
}

function writeBlock(file, json) {
  const p = path.join(ROOT, file);
  let text = fs.readFileSync(p, 'utf8');
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  if (a < 0 || b < 0) throw new Error('markers not found in ' + file);
  /* Verify before writing. A malformed block is worse than none:
     search engines discard the lot rather than the bad part. */
  JSON.parse(json);
  const block = BEGIN + '\n<script type="application/ld+json">\n' + json + '\n</script>\n' + END;
  fs.writeFileSync(p, text.slice(0, a) + block + text.slice(b + END.length));
  return p;
}

/* ---- the Help Center's own questions ---- */
function faq() {
  const file = 'pages/help-center.html';
  const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
  /* <dt> then <dd>, in the order the page has them. */
  const pairs = [];
  const re = /<dt\b[^>]*>([\s\S]*?)<\/dt>\s*<dd\b[^>]*>([\s\S]*?)<\/dd>/g;
  let m;
  while ((m = re.exec(html))) {
    const q = plain(m[1]);
    const a = plain(m[2]);
    if (q && a) pairs.push({ q, a });
  }
  if (!pairs.length) throw new Error('no question and answer pairs found in ' + file);

  const doc = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    '@id': 'https://caprock-storage.com/help-center#faq',
    about: { '@id': BUSINESS },
    mainEntity: pairs.map((p) => ({
      '@type': 'Question',
      name: p.q,
      acceptedAnswer: { '@type': 'Answer', text: p.a },
    })),
  };
  writeBlock(file, JSON.stringify(doc, null, 2));
  return pairs.length;
}

/* ---- every size, from the feed the page itself reads ---- */
async function catalogue() {
  const url = ENDPOINT + '?facility=' + encodeURIComponent(FACILITY) + '&resource=movein';
  const r = await fetch(url);
  if (!r.ok) throw new Error('movein returned ' + r.status);
  const units = (((await r.json()) || {}).unitTypes || [])
    .filter((u) => u && u.width && u.length && Number(u.rate) > 0)
    .sort((a, b) => (Number(a.sqft) || 0) - (Number(b.sqft) || 0));
  if (!units.length) throw new Error('the feed returned no priced unit types');

  const rates = units.map((u) => Number(u.rate));
  const size = (u) => [u.width, u.length].map(Number).join(' x ') +
    (u.height ? ' x ' + Number(u.height) : '');

  const doc = {
    '@context': 'https://schema.org',
    '@type': 'OfferCatalog',
    '@id': 'https://caprock-storage.com/lubbock-2213-n-quaker#units',
    name: 'Storage unit sizes and rates, CapRock Self Storage, Lubbock',
    provider: { '@id': BUSINESS },
    itemListElement: units.map((u, i) => ({
      '@type': 'Offer',
      position: i + 1,
      name: size(u) + ' ft ' + (u.climate ? 'temperature controlled' : 'drive-up') + ' storage unit',
      price: Number(u.rate),
      priceCurrency: 'USD',
      availability: Number(u.vacantCount) > 0
        ? 'https://schema.org/InStock'
        : 'https://schema.org/OutOfStock',
      /* Rent is monthly and the leases are month to month, so the
         price is a unit price with a month as its reference. */
      priceSpecification: {
        '@type': 'UnitPriceSpecification',
        price: Number(u.rate),
        priceCurrency: 'USD',
        unitCode: 'MON',
        billingDuration: 1,
      },
      itemOffered: {
        '@type': 'Product',
        name: size(u) + ' ft storage unit',
        category: u.climate ? 'Temperature controlled self storage' : 'Drive-up self storage',
        ...(u.sqft ? { additionalProperty: {
          '@type': 'PropertyValue', name: 'Floor area', value: Number(u.sqft), unitCode: 'FTK',
        } } : {}),
      },
    })),
    lowPrice: Math.min(...rates),
    highPrice: Math.max(...rates),
    priceCurrency: 'USD',
  };
  writeBlock('pages/lubbock-2213-n-quaker.html', JSON.stringify(doc, null, 2));
  return units.length;
}

(async () => {
  const n = faq();
  console.log('help-center.html      FAQPage, ' + n + ' questions');
  const m = await catalogue();
  console.log('lubbock-...html       OfferCatalog, ' + m + ' sizes');
  console.log('\nNow: bash tools/build-preview.sh && node tools/check.js');
})().catch((e) => {
  console.error('failed:', e.message);
  process.exit(1);
});
