/* Generate the structured data that has a source of truth elsewhere.

   The business itself is written by hand in global-sections/header.html,
   because its facts are stable and few. These two are not:

     FAQPage        the 25 questions in help-center.html. Kept in step
                    by reading that page's own <dl> pairs, so the
                    answer a machine gets is the answer a visitor
                    reads, and editing one cannot silently leave the
                    other behind.

     OfferCatalog   every size and rate on the location page, read
                    from the live feed and priced by the site's own
                    helper, so the price a search engine quotes is the
                    price the page shows.

   RUN IT after editing the Help Center, or when rates or offers change:
     node tools/build-schema.js

   It rewrites only what is between the BEGIN and END markers. */
'use strict';

const fs = require('fs');
const path = require('path');
const { loadPriced, numbers } = require('./_wss');

const ROOT = path.join(__dirname, '..');
const BUSINESS = 'https://caprock-storage.com/#business';

const BEGIN = '<!-- BEGIN SCHEMA: generated by tools/build-schema.js, do not hand edit -->';
const END = '<!-- END SCHEMA -->';

/* ---- turning markup back into text ----
   The answers contain links and non-breaking spaces. Structured data
   wants the sentence a person would read aloud, so the tags come out
   and the entities go back to being characters. */
const ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ',
  hellip: '…', times: '×', ndash: '–', mdash: '—',
  rsquo: '’', lsquo: '‘', ldquo: '“', rdquo: '”',
  copy: '©', deg: '°',
};

function plain(html) {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&(\w+);/g, (_, n) => (ENTITIES[n] !== undefined ? ENTITIES[n] : '&' + n + ';'))
    .replace(/\s+/g, ' ')
    .trim();
}

function writeBlock(file, json) {
  const p = path.join(ROOT, file);
  const text = fs.readFileSync(p, 'utf8');
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  if (a < 0 || b < 0) throw new Error('markers not found in ' + file);
  /* Verify before writing. A malformed block is worse than none:
     search engines discard the lot rather than the bad part. */
  JSON.parse(json);
  const block = BEGIN + '\n<script type="application/ld+json">\n' + json + '\n</script>\n' + END;
  fs.writeFileSync(p, text.slice(0, a) + block + text.slice(b + END.length));
}

/* ---- the Help Center's own questions ---- */
function faq() {
  const file = 'pages/help-center.html';
  const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
  /* <dt> then <dd>, in the order the page has them. */
  const pairs = [];
  const re = /<dt\b[^>]*>([\s\S]*?)<\/dt>\s*<dd\b[^>]*>([\s\S]*?)<\/dd>/g;
  let m;
  while ((m = re.exec(html))) {
    const q = plain(m[1]);
    const a = plain(m[2]);
    if (q && a) pairs.push({ q, a });
  }
  if (!pairs.length) throw new Error('no question and answer pairs found in ' + file);

  const doc = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    '@id': 'https://caprock-storage.com/help-center#faq',
    about: { '@id': BUSINESS },
    mainEntity: pairs.map((p) => ({
      '@type': 'Question',
      name: p.q,
      acceptedAnswer: { '@type': 'Answer', text: p.a },
    })),
  };
  writeBlock(file, JSON.stringify(doc, null, 2));
  return pairs.length;
}

/* ---- every size, priced the way the page prices it ----
   Offer.price is what a customer would be quoted today, because that
   is the figure on the page, and a search result that contradicts the
   page is worse than no search result at all.

   The list price is not thrown away. It rides along as a second
   priceSpecification tagged ListPrice, which is schema.org's own way
   of saying "this was the price", and the promotion's length goes in
   referenceQuantity. So an engine that quotes the low number has the
   terms attached to it, rather than having to assume a promotional
   rate lasts forever.

   No sums happen here. bestOffer and pricing come out of the header
   through _wss.js, so this cannot drift from what visitors see. */
const PAGE = 'https://caprock-storage.com/lubbock-2213-n-quaker';
const PHOTO = 'https://assets.cdn.filesafe.space/Al1OnFCjf6Mtgmi0CTtF/media/6aad95be30b0f957cc778a42.jpg';

async function catalogue() {
  const { wss, units } = await loadPriced();
  if (!units.length) throw new Error('the feed returned no priced unit types');

  const size = (u) => [u.width, u.length].map(Number).join(' x ') +
    (u.height ? ' x ' + Number(u.height) : '');
  const charged = units.map((u) => numbers(wss, u).now);

  const doc = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    '@id': PAGE + '#units',
    name: 'Storage unit sizes and rates, CapRock Self Storage, Lubbock',
    numberOfItems: units.length,
    itemListElement: units.map((u, i) => {
      const n = numbers(wss, u);
      const p = wss.pricing(u);
      const terms = p ? [p.label, p.then].filter(Boolean).join(', ') : '';

      /* What is charged today, first. */
      const spec = [Object.assign({
        '@type': 'UnitPriceSpecification',
        price: n.now,
        priceCurrency: 'USD',
        unitCode: 'MON',
        billingDuration: 1,
      }, n.discounted && n.months
        ? { referenceQuantity: { '@type': 'QuantitativeValue', value: n.months, unitCode: 'MON' } }
        : {})];

      /* And what it was, and returns to. */
      if (n.discounted) {
        spec.push({
          '@type': 'UnitPriceSpecification',
          priceType: 'https://schema.org/ListPrice',
          price: n.list,
          priceCurrency: 'USD',
          unitCode: 'MON',
          billingDuration: 1,
        });
      }

      const product = Object.assign({
        '@type': 'Product',
        '@id': PAGE + '#unit-' + size(u).replace(/ /g, ''),
        name: size(u) + ' ft ' + (u.climate ? 'temperature controlled' : 'drive-up') + ' storage unit',
        image: PHOTO,
        category: u.climate ? 'Temperature controlled self storage' : 'Drive-up self storage',
      }, terms ? { description: terms } : {}, u.sqft ? {
        additionalProperty: {
          '@type': 'PropertyValue', name: 'Floor area', value: Number(u.sqft), unitCode: 'FTK',
        },
      } : {}, {
        /* The offer hangs off the product, not the other way round.
           Nested the other way this validated as thirteen Products
           with no price on any of them, and Google rejected all
           thirteen: a Product has to carry offers, review or
           aggregateRating, and itemOffered does not count. */
        offers: {
          '@type': 'Offer',
          url: PAGE + '#units',
          price: n.now,
          priceCurrency: 'USD',
          availability: Number(u.vacantCount) > 0
            ? 'https://schema.org/InStock'
            : 'https://schema.org/OutOfStock',
          seller: { '@id': BUSINESS },
          priceSpecification: spec,
        },
      });

      return { '@type': 'ListItem', position: i + 1, item: product };
    }),
  };
  writeBlock('pages/lubbock-2213-n-quaker.html', JSON.stringify(doc, null, 2));
  return {
    count: units.length,
    low: Math.min.apply(null, charged),
    high: Math.max.apply(null, charged),
  };
}

(async () => {
  const n = faq();
  console.log('help-center.html      FAQPage, ' + n + ' questions');
  const c = await catalogue();
  console.log('lubbock-...html       ItemList, ' + c.count + ' products, 
  console.log('\nNow: bash tools/build-preview.sh && node tools/check.js');
})().catch((e) => {
  console.error('failed:', e.message);
  process.exit(1);
});
 + c.low + ' to 
  console.log('\nNow: bash tools/build-preview.sh && node tools/check.js');
})().catch((e) => {
  console.error('failed:', e.message);
  process.exit(1);
});
 + c.high);
  console.log('\nNow: bash tools/build-preview.sh && node tools/check.js');
})().catch((e) => {
  console.error('failed:', e.message);
  process.exit(1);
});
