/* Put the Google reviews into the pages as real HTML.

   WHY THIS IS A BUILD STEP AND NOT A SCRIPT ON THE PAGE
   The whole point of putting reviews on the site is that the answer
   engines read them. GPTBot, ClaudeBot, PerplexityBot and Common
   Crawl do not run JavaScript, so a reviews section drawn by script
   would be invisible to exactly the readers it is for. That mistake
   already cost this site its prices for a while. So the markup is
   written into the files, from one source, by this.

   WHY NOT structured data
   Google disallows self-serving reviews: reviews about a business,
   published on that business's own site. Marking these up as an
   aggregateRating on our SelfStorage block would at best be ignored
   and at worst draw a manual action. They already count where they
   live, on the Business Profile. Here they are prose, for the models
   that read prose.

   RUN IT when a review is added or the profile URL is set:
     node tools/build-reviews.js
   Then rebuild the previews and repaste the two pages.

   It rewrites only what is between the BEGIN and END markers. */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BEGIN = '<!-- BEGIN REVIEWS: generated by tools/build-reviews.js, do not hand edit -->';
const END = '<!-- END REVIEWS -->';

const esc = (v) => String(v == null ? '' : v)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* Filled stars up to the rating, hollow after. The label carries the
   number, because a screen reader should not have to count glyphs. */
function stars(n) {
  const filled = Math.max(0, Math.min(5, Math.round(Number(n) || 0)));
  return '<p class="crss-review-stars" role="img" aria-label="' + filled + ' out of 5 stars">' +
    '★'.repeat(filled) + '☆'.repeat(5 - filled) + '</p>';
}

function section(data, heading) {
  const list = (data.reviews || []).filter((r) => r && r.name && r.text);
  if (!list.length) throw new Error('reviews.json has no usable reviews');

  const items = list.map((r) => '          <li class="crss-review">\n' +
    '            ' + stars(r.stars) + '\n' +
    '            <blockquote class="crss-review-text">' + esc(r.text) + '</blockquote>\n' +
    '            <p class="crss-review-by">' + esc(r.name) +
    '<span>' + esc(r.when || '') + '</span></p>\n' +
    '          </li>').join('\n');

  /* A dead link is worse than no link, so this only appears once
     someone has put the profile URL in reviews.json. */
  const all = data.profileUrl
    ? ' <a class="crss-reviews-all" href="' + esc(data.profileUrl) +
      '" target="_blank" rel="noopener">Read them all on Google</a>'
    : '';

  return BEGIN + '\n' +
    '      <section class="crss-reviews">\n' +
    '        <p class="crss-reviews-eyebrow">Reviews</p>\n' +
    '        <h2 class="crss-reviews-title">' + esc(heading) + '</h2>\n' +
    '        <p class="crss-reviews-lede">Left on Google by people who rent here.' + all + '</p>\n' +
    '        <ul class="crss-review-list">\n' + items + '\n' +
    '        </ul>\n' +
    '      </section>\n' +
    '      ' + END;
}

function replaceBlock(file, block) {
  const p = path.join(ROOT, file);
  const text = fs.readFileSync(p, 'utf8');
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  if (a < 0 || b < 0) throw new Error('markers not found in ' + file);
  fs.writeFileSync(p, text.slice(0, a) + block + text.slice(b + END.length));
}

const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'reviews.json'), 'utf8'));

[
  ['pages/home.html', 'What our tenants say'],
  ['pages/lubbock-2213-n-quaker.html', 'What tenants say about this location'],
].forEach(([f, heading]) => {
  replaceBlock(f, section(data, heading));
  console.log('wrote ' + f);
});

const n = (data.reviews || []).length;
console.log('\n' + n + ' reviews.');
if (!data.profileUrl) {
  console.log('profileUrl is empty in data/reviews.json, so the "read them all"');
  console.log('link is not rendered. Set it to the public Google reviews URL.');
}
console.log('\nNow: bash tools/build-preview.sh && node tools/check.js');
